Blog/models.py
class PostUI:
    def __init__(self):
        self.__author_name = ''
        self.__author_id = -10000
        self.__body = ''
        self.__post_title = ''
    def save(self):
        pass
    def get(self):
        pass
    @property
    def author_name(self):
        return self.__author_name
    @author_name.setter
    def author_name(self, author_name):
        if (author_name == '') or (author_name is None):
            raise ValueError('The author name can not be  null or blank!')
        else:
            self.__author_name = author_name
    @property
    def author_id(self):
        return self.__author_id
    @author_id.setter
    def author_id(self, author_id):
        if (author_id is None) or (author_id <= 0):
            raise ValueError('The author is is not null or <= 0')
        else:
            self.__author_id = author_id
    @property
    def post_body(self):
        return self.__body
    @post_body.setter
    def post_body(self, body):
        if not  isinstance(body, str):
            raise ValueError('The post must be a string!')
        else:
            self.__body = body
    @property
    def post_title(self):
        return self.__post_title
    @post_title.setter
    def post_title(self, title):
        if title == '' or title is None:
            raise ValueError('The title can not be null or blank!')
        else:
            self.__post_title = title

Blog/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired

class Editor(FlaskForm):
    title = StringField("title", validators=[DataRequired()])
    text = TextAreaField("text",         
        id="target-editor-twitter", validators=[DataRequired()])
    tags = StringField("tags", validators=[DataRequired()])
    draft = BooleanField("draft", default=False)
    submit = SubmitField("submit")

Blog/__init__.py
from flask import Blueprint, Flask
from Blog.views import index, post_by_author, post_body, post_editor
from flask_bootstrap import Bootstrap
from Blog import config

def __addurlrule(blogblueprint):
    blogblueprint.add_url_rule('/', endpoint=None, view_func=index)
    blogblueprint.add_url_rule('/post/<string:author>', view_func=post_by_author)
    blogblueprint.add_url_rule('/post/<int:Id>', view_func=post_body)
    blogblueprint.add_url_rule('/post/editor/<int:Id>', view_func=post_editor)
#
def create_blueprint():
    blog_blueprint = Blueprint('blog', __name__,
                               template_folder='templates',
                               static_folder='static')
#
    __addurlrule(blog_blueprint)
    return blog_blueprint
#
def init_app(app, config_name):
    bootstrap = Bootstrap(app)
    if  not isinstance(app, Flask):
        raise TypeError('app is not an instance of class Flask')
    blog_blue= create_blueprint()
    blog_blue.static_url_path=app.static_url_path + "/blog"
    app.register_blueprint(blog_blue)
    app.config.from_object(config.config[config_name])
    config.config[config_name].init_app(app)
    

Blog/flask_auth/__init__.py
#!/user/bin/env python
# coding=utf8

from .auth import auth, FlaskAuth

Blog/flask_auth/auth.py
from flask import Blueprint
from flask_bootstrap import Bootstrap
from .views import login, logout

def __create_blueprint():
    auth  = Blueprint(
                "auth",
                __name__,
                template_folder="templates",
                static_folder="static"            
            )
    auth.add_url_rule("/loging", endpoint=None, view_func=login, methods=['POST'])
    auth.add_url_rule("/logout", endpoint=None, view_func=logout)
    return auth
auth = __create_blueprint()

class FlaskAuth():

    def __init__(self, app=None):
        if app is not None:
            self.init_app(app)
        else:
            self.__app = None
    
    def init_app(self, app):
        self.__app = app
        auth.static_url_path = static_url_path=app.static_url_path + "auth"
        self.__add__bootstrap__(app)
        app.register_blueprint(auth)
    
    def __add__bootstrap__(self, app):
        some = 'bootstrap' in  app.blueprints
        if some  is not True:
            Bootstrap(app)

Blog/flask_auth/views.py
from flask import flash, redirect, render_template, abort, session, request


def login():
    return "还未实现！"


def logout():
    return "还未实现！"

Blog/views.py
from flask import render_template, url_for, redirect
from .Models.modelsUI import PostUI
from .forms import Editor


def __get_test_posts():
    post_title = "How To Start a Blog – Beginner’s Guide for 2017"
    post_content = "The emergence and growth of blogs in the late 1990s coincided with the advent of web publishing tools that facilitated the posting of content by non-technical users who did not have much experience with HTML or computer programming. Previously, a knowledge of such technologies as HTML and File Transfer Protocol had been required to publish content on the Web, and as such, early Web users tended to be hackers and computer enthusiasts. In the 2010s, the majority are interactive Web 2.0 websites, allowing visitors to leave online comments, and it is this interactivity that distinguishes them from other static websites.[2] In that sense, blogging can be seen as a form of social networking service. Indeed, bloggers do not only produce content to post on their blogs, but also often build social relations with their readers and other bloggers.[3] However, there are high-readership blogs which do not allow comments."
    posts = []
    post = PostUI()
    post.author_id = 1
    post.author_name = '匡飞龙'
    post.post_title = post_title
    post.post_body = post_content
    post.post_id = 1000
    posts.append(post)
    posts.append(post)
    return posts
def __get_entries_by_author(author):
    __posts=[]
    __posts.append(__get_test_posts()[0])
    return __posts
#dishplay all the post entries
def index():
    return render_template('index.html', posts=__get_test_posts())
#display all the post entries of the author
def post_by_author(author):
    _posts = __get_entries_by_author(author)
    return render_template('index.html', posts=_posts)
def post_body(Id):
    posts = __get_entries_by_author("")
    return render_template("post_body.html", post=posts[0])
def post_editor(Id):
    form = Editor()
    return render_template("editor.html", form=form)

Blog/templates/base.html
{% extends "bootstrap/base.html" %} 
{% block title %}混凝土工程博客{% endblock %} 
{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">主页</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">索引</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %} 
{% block content %}
    <div class="container-fluid">
        <div class="row" >
            <div class="col-sm-8" style="background-color:lavenderblush;">
               {% block left_content %}{% endblock %}
            </div>
            <div class="col-sm-4" style="background-color:lavender;">
                {% block right_content %}
                    
                {% endblock %}
            </div>
        </div>
    <div class="container-fluid">
        <div class="row" style="background-color:darkgray">
            <footer>
                {% block footer_content%}
                    <h2>The footer content has not implemented!</h2>
                {% endblock %}
            </footer>
        </div>
    </div>
{% endblock %}

Blog/templates/editor.html
{% extends "base.html" %}
{% block head %}
    {{super()}}   
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML">
        MathJax.Hub.Config({
            tex2jax: {
                inlineMath: [['$','$'], ['\\(','\\)']],
                processEscapes: true
            }
        });
    </script>        
{% endblock head %}
{% block metas %}
    {{super()}}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
{% endblock metas %}
{% block styles %}
    <link rel="stylesheet" 
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" 
        crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" 
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" 
        integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" 
        crossorigin="anonymous">
{% endblock styles %}

{% block left_content %}
    <form> 
    <div class="form-group" >
    <label class="control-label col-md-offset-2  control-label input-md" for="title">
    Title
    </label>
    <div class="input-group col-md-8 col-md-offset-2">
    {{form.title(placeholder="Title", id="title", required="" )}}
    </div>
    </div>

    <div class="form-group">
    <div class="input-group col-md-8 col-md-offset-2">
    {{form.text(data_width="500", rows="20")}}
    <span class="help-block">
    Learn more about <a href="https://zh.wikipedia.org/wiki/Markdown" target="_blank">MarkDown</a><br>
    </span>
    <span class="help-block">
    learn more about  <a href="https://zh.wikipedia.org/wiki/Help:%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F" target="_blank">latex数学公式</a>
    </span>
    </div>
    </div>
    <!-- Text input-->
    <div class="form-group">
    <label class="col-md-offset-2 control-label" for="tags">Tags</label>
    <div class="input-group col-md-8 col-md-offset-2">
    {{form.tags}}
    </div>
    </div>

    <div class="form-group">
    <div class="col-md-offset-2">
    {{ form.submit(id="submit", class="btn btn-primary") }}
    </div>
    </div>
    </form>                  
{% endblock left_content%}
{% block right_content %}
    <h3>preview</h3>
    <div id="preview"   style="width: 400" >
        <p>$$\frac{-b\pm\sqrt{b^2-4ac}}{2a}$$</p>
    </div>               
{% endblock right_content %}

{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script 
        src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" 
        crossorigin="anonymous"></script>
    <script 
        src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js" 
        type="text/javascript"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-markdown/2.10.0/js/bootstrap-markdown.js">
    </script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/pagedown/1.0/Markdown.Converter.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/pagedown/1.0/Markdown.Sanitizer.min.js"></script>
    <script src="/static/js/markdown.js"></script>
    <script src="/static/js/to-markdown.js"></script>
    <script src="/static/js/main.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){            
            $("div.md-controls").remove()            
            $("div.md-fullscreen-controls").remove()
            
        })
        $("#some-textarea").markdown(
            {
                autofocus: false,
                savable: false,
                resize: "both",
                footer: "",
                fullscreen:"",
                
            })
        $("#target-editor-twitter").markdown({
            onShow:function(e){
                e.hideButtons("cmdPreview")
            },
            onChange: function(e){
                parsed_markdown = e.parseContent()
                div_preview=document.getElementById("preview")
                div_preview.innerHTML = parsed_markdown
                MathJax.Hub.Typeset();
            }            
        })            
        
    </script>
   
  
{% endblock scripts %}

Blog/templates/index.html
{% extends "base.html"%}
{%block left_content %}
    <div>
        {% for post in posts %}    
           {% include 'post_entry.html' %}
        {% endfor %}
    </div>
{%endblock%}
{% block right_content %}
    <h3>分类还未实现</h3>                    
{% endblock %}

Blog/templates/pagedown-bootstrap.html
{% extends "bootstrap/base.html" %}
{% block title %}This is an example page{% endblock %}

{% block navbar %}
<div class="navbar navbar-fixed-top">
  <!-- ... -->
</div>
{% endblock %}

{% block content %}
    <form class="form form-horizontal" method="post" role="form">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, hiddens="only") }}

        {{ wtf.form_field(form.field1) }}
        {{ wtf.form_field(form.field2) }}
        {{ wtf.form_field(form.field3) }}
    </form>
{% endblock %}

Blog/templates/post_base.html
<div>
    <a href= "{{ url_for('blog.post_by_author', author=post.author_name) }}">{{post.author_name}}</a>
    <a href="{{url_for('blog.post_body', Id=post.post_id)}}"><h1>{{post.post_title}}</h1></a>
    {% block post %}
    {% endblock%}        
    <br/>
    <br/>    
</div>

Blog/templates/post_body.html
{% extends "base.html" %}
{% block left_content %}
    {% include "post_full_text.html" %}
{% endblock %}

Blog/templates/post_editor.html
{% extends 'base.html' %}
{% block left_content %}
    
{% endblock %}

Blog/templates/post_entry.html
{% extends "post_base.html"%}
{% block post %}
    <div><h2>{{post.get_first_paragraph}}</h2>
        <a href="{{url_for('blog.post_body', Id=post.post_id)}}">阅读全文</a>
    </div>
    <br/>
    <br/>
{% endblock %}

Blog/templates/post_full_text.html
{% extends "post_base.html" %}
{% block post %}
    <div>{{post.post_body}}</div>
    <div>
        <br/>
        <br/>
        <a href="{{url_for( 'blog.post_editor', Id= 3 ) }}">编辑</a>
    </div>
    {%block Comment_area %}
        <h2>评论区还未实现</h2>
    {%endblock%}
{% endblock %}

Blog/templates/some.html
<!doctype html>
<html>
    <a href= "{{ url_for('page', user=name)}}" ><h1>some</h1></a>
</html>